# Generated by Django 5.0.6 on 2024-05-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0003_alter_expensecategory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('housing', 'Housing'), ('clothing', 'Clothing'), ('health', 'Health'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('housing', 'Housing'), ('clothing', 'Clothing'), ('health', 'Health'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('others', 'Others')], max_length=100),
        ),
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.AlterField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10),
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
