# Generated by Django 5.0.6 on 2024-05-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0005_expense_receipt_income_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='income',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='income',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
