# Generated by Django 5.0.6 on 2024-05-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0006_expense_recurring_income_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='divisions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='expense',
            name='recovered',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='expense',
            name='split',
            field=models.BooleanField(default=False),
        ),
    ]
