# Generated by Django 5.0.6 on 2024-05-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalfinance', '0007_expense_divisions_expense_recovered_expense_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(default='2021-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(default='2021-01-01 00:00:00'),
        ),
    ]
